In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dpath = "/content/drive/MyDrive/contest/Git_Contest/data/"

In [14]:
public = pd.read_csv (dpath+'전국공공체육시설데이터.csv')

In [15]:
public.head()

,FACI_NM,FACI_GB_CD,FACI_GB_NM,FCOB_CD,FCOB_NM,FTYPE_CD,FTYPE_NM,FMNG_TYPE_GB_CD,FMNG_TYPE_GB_NM,FMNG_CP_CD,...,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y,TOT_FACI_AREA,STAND_CPT_PSN_CNT,STAND_SEAT_CNT,FACI_HOMEPAGE,NATION_YN,FACI_STAT,DEL_YN
0,(외립석입구),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,N
1,(자산경로당),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771,NaN,NaN,NaN,NaN,N,0,N
2,신리 봉계초등학교 (강당뒤),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,N
3,신리 봉계초등학교 (강당뒤),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,Y
4,성당뒤,P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,Y

In [23]:
public.info() # null값이 많은 컬럼순으로 결측치를 처리해볼까? 일단 ADDR_AMD_CD, ADDR_AMD_NM 이 두 변수는 모든 값이 null이라 컬럼 삭제할게

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31138 entries, 0 to 31137
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FACI_NM          31138 non-null  object
 1   FACI_GB_CD       31138 non-null  object
 2   FACI_GB_NM       31138 non-null  object
 3   FCOB_CD          31138 non-null  object
 4   FCOB_NM          31138 non-null  object
 5   FTYPE_CD         31138 non-null  object
 6   FTYPE_NM         31138 non-null  object
 7   FMNG_TYPE_GB_CD  30673 non-null  float64
 8   FMNG_TYPE_GB_NM  30673 non-null  object
 9   FMNG_CP_CD       31128 non-null  float64
 10  FMNG_CP_NM       31128 non-null  object
 11  FMNG_CPB_CD      31128 non-null  float64
 12  FMNG_CPB_NM      31128 non-null  object
 13  ADDR_CP_CD       31137 non-null  float64
 14  ADDR_CP_NM       31006 non-null  object
 15  ADDR_CPB_CD      31048 non-null  float64
 16  ADDR_CPB_NM      30835 non-null  object
 17  FACI_POINT_X     27781 non-null  float64
 18  FACI_POINT_Y     27781 non-null  float64
 19  NATION_YN        31138 non-null  object
 20  FACI_STAT        31138 non-null  int64
 21  DEL_YN           31138 non-null  object
dtypes: float64(7), int64(1), object(14)
memory usage: 5.2+ MB

In [17]:
public = public.drop(['ADDR_AMD_CD', 'ADDR_AMD_NM'], axis=1)

In [18]:
public = public.drop(['STAND_CPT_PSN_CNT', 'STAND_SEAT_CNT'], axis=1) # 수용인원, 관람석도 무의미해서 삭제

In [19]:
public = public.drop(['TOT_FACI_AREA', 'FACI_HOMEPAGE','FMNG_DEPT_NM','FMNG_USER_TEL'], axis=1) # 시설면적(㎡), 홈페이지, 담당자 부서, 담당자 연락처도 자료수 적고 무의미해서 삭제

ADDR_EMD_CD 도로명 동읍면코드
ADDR_EMD_NM 도로명 동읍면명
FACI_ROAD_ADDR1 도로명 주소
이 변수들은 이렇게까지 자세한 주소가 필요할까 싶어서 삭제해도 될듯? null값도 많기도하고..

In [22]:
public = public.drop(['ADDR_EMD_CD', 'ADDR_EMD_NM','FACI_ROAD_ADDR1'], axis=1)